# -----------------------------------------------
# Cloud Build pipeline for Lugx Frontend
# This file:
# 1. Builds Docker image from frontend folder
# 2. Pushes to Artifact Registry
# 3. Replaces placeholder in deployment YAML
# 4. Deploys frontend to GKE
# 5. Exposes it using a Kubernetes LoadBalancer
# -----------------------------------------------

steps:
  # Step 1: Build Docker image from frontend/
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/lugx-docker-repo/lugx-frontend:$SHORT_SHA',
        '.'
      ]
    dir: 'frontend'  # Dockerfile is inside the frontend directory

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/$PROJECT_ID/lugx-docker-repo/lugx-frontend:$SHORT_SHA'
      ]

  # Step 3: Replace placeholder IMAGE in the deployment YAML
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        sed "s|IMAGE_PLACEHOLDER|us-central1-docker.pkg.dev/$PROJECT_ID/lugx-docker-repo/lugx-frontend:$SHORT_SHA|" frontend/frontend-deployment.yaml > frontend/k8s-frontend-deployment.yaml

  # Step 4: Apply updated deployment file to GKE cluster
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'frontend/k8s-frontend-deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=lugx-cluster'

  # Step 5: Apply the frontend service file to expose app to the internet
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'frontend/frontend-service.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=lugx-cluster'

# Optional: Declare the output image so it shows in GCP UI
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/lugx-docker-repo/lugx-frontend:$SHORT_SHA'

# ✅ Fix: Log only to Google Cloud Logging (no GCS bucket needed)
options:
  logging: CLOUD_LOGGING_ONLY