apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80        # Public port
      targetPort: 3000 # Container port
  type: LoadBalancer